version: '3.5'
services:
  db:
    build: ./db
    networks:
      - new-network
  http:
    build: .
    command: node server.js
    volumes:
      - /http-microservice
    networks:
      - new-network
    ports:
      - "4000:3306"
      - "5000:8080"
    depends_on:
      - "db"
networks:
  new-network:
    name: new-network-latihan
    driver: bridge